# coding: utf-8

"""
    Secure Email Gateway API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.spam_quarantine_api import SpamQuarantineApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSpamQuarantineApi(unittest.TestCase):
    """SpamQuarantineApi unit test stubs"""

    def setUp(self):
        self.api = SpamQuarantineApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_esa_api_v20_quarantine_blocklist_delete(self):
        """Test case for esa_api_v20_quarantine_blocklist_delete

        Delete blocklist entries  # noqa: E501
        """
        pass

    def test_esa_api_v20_quarantine_blocklist_get(self):
        """Test case for esa_api_v20_quarantine_blocklist_get

        Retrieve Blocklist entries  # noqa: E501
        """
        pass

    def test_esa_api_v20_quarantine_blocklist_post(self):
        """Test case for esa_api_v20_quarantine_blocklist_post

        Add, edit and append Blocklist entries  # noqa: E501
        """
        pass

    def test_esa_api_v20_quarantine_messages_delete(self):
        """Test case for esa_api_v20_quarantine_messages_delete

        Delete messages that match various attribute  # noqa: E501
        """
        pass

    def test_esa_api_v20_quarantine_messages_details_get(self):
        """Test case for esa_api_v20_quarantine_messages_details_get

        Retrieve details of a message that match multiple attributes  # noqa: E501
        """
        pass

    def test_esa_api_v20_quarantine_messages_get(self):
        """Test case for esa_api_v20_quarantine_messages_get

        Search for messages in the spam quarantine that match multiple attributes  # noqa: E501
        """
        pass

    def test_esa_api_v20_quarantine_messages_post(self):
        """Test case for esa_api_v20_quarantine_messages_post

        Release messages that match various attribute  # noqa: E501
        """
        pass

    def test_esa_api_v20_quarantine_safelist_delete(self):
        """Test case for esa_api_v20_quarantine_safelist_delete

        Delete safelist entries  # noqa: E501
        """
        pass

    def test_esa_api_v20_quarantine_safelist_get(self):
        """Test case for esa_api_v20_quarantine_safelist_get

        Retrieve Safelist entries  # noqa: E501
        """
        pass

    def test_esa_api_v20_quarantine_safelist_post(self):
        """Test case for esa_api_v20_quarantine_safelist_post

        Add, edit and append Safelist entries  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
