# coding: utf-8

"""
    Secure Email Gateway API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.message_tracking_api import MessageTrackingApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMessageTrackingApi(unittest.TestCase):
    """MessageTrackingApi unit test stubs"""

    def setUp(self):
        self.api = MessageTrackingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_esa_api_v20_message_tracking_amp_details_get(self):
        """Test case for esa_api_v20_message_tracking_amp_details_get

        Retrieve details of AMP action details of messages with different attributes  # noqa: E501
        """
        pass

    def test_esa_api_v20_message_tracking_connection_details_get(self):
        """Test case for esa_api_v20_message_tracking_connection_details_get

        Retrieve connection details of messages with different attributes  # noqa: E501
        """
        pass

    def test_esa_api_v20_message_tracking_details_get(self):
        """Test case for esa_api_v20_message_tracking_details_get

        Retrieve details of messages with different attributes  # noqa: E501
        """
        pass

    def test_esa_api_v20_message_tracking_dlp_details_get(self):
        """Test case for esa_api_v20_message_tracking_dlp_details_get

        Retrieve details of DLP of messages with different attributes  # noqa: E501
        """
        pass

    def test_esa_api_v20_message_tracking_messages_get(self):
        """Test case for esa_api_v20_message_tracking_messages_get

        Message-tracking messages  # noqa: E501
        """
        pass

    def test_esa_api_v20_message_tracking_url_details_get(self):
        """Test case for esa_api_v20_message_tracking_url_details_get

        Retrieve details of URL details of messages with different attributes  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
