# coding: utf-8

"""
    Secure Email Gateway API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.safelist_api import SafelistApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSafelistApi(unittest.TestCase):
    """SafelistApi unit test stubs"""

    def setUp(self):
        self.api = SafelistApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_esa_api_v20_quarantine_safelist_delete(self):
        """Test case for esa_api_v20_quarantine_safelist_delete

        Delete safelist entries  # noqa: E501
        """
        pass

    def test_esa_api_v20_quarantine_safelist_get(self):
        """Test case for esa_api_v20_quarantine_safelist_get

        Retrieve Safelist entries  # noqa: E501
        """
        pass

    def test_esa_api_v20_quarantine_safelist_post(self):
        """Test case for esa_api_v20_quarantine_safelist_post

        Add, edit and append Safelist entries  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
