# coding: utf-8

"""
    Secure Email Gateway API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.reporting_mail_dlp_outgoing_policy_detail_dlp_action_delivered_data import ReportingMailDlpOutgoingPolicyDetailDlpActionDeliveredData  # noqa: E501
from swagger_client.rest import ApiException


class TestReportingMailDlpOutgoingPolicyDetailDlpActionDeliveredData(unittest.TestCase):
    """ReportingMailDlpOutgoingPolicyDetailDlpActionDeliveredData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReportingMailDlpOutgoingPolicyDetailDlpActionDeliveredData(self):
        """Test ReportingMailDlpOutgoingPolicyDetailDlpActionDeliveredData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.reporting_mail_dlp_outgoing_policy_detail_dlp_action_delivered_data.ReportingMailDlpOutgoingPolicyDetailDlpActionDeliveredData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
