# coding: utf-8

"""
    Secure Email Gateway API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.config_log_subscriptions_get import ConfigLogSubscriptionsGet  # noqa: E501
from swagger_client.rest import ApiException


class TestConfigLogSubscriptionsGet(unittest.TestCase):
    """ConfigLogSubscriptionsGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfigLogSubscriptionsGet(self):
        """Test ConfigLogSubscriptionsGet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.config_log_subscriptions_get.ConfigLogSubscriptionsGet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
