# coding: utf-8

"""
    Secure Email Gateway API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.mail_env_sender_rate_limit_api import MailEnvSenderRateLimitApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMailEnvSenderRateLimitApi(unittest.TestCase):
    """MailEnvSenderRateLimitApi unit test stubs"""

    def setUp(self):
        self.api = MailEnvSenderRateLimitApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_esa_api_v20_reporting_mail_env_sender_rate_limit_env_sender_incidents_get(self):
        """Test case for esa_api_v20_reporting_mail_env_sender_rate_limit_env_sender_incidents_get

        mail env sender rate limit env sender incidents  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_env_sender_rate_limit_env_sender_rejected_rcpts_get(self):
        """Test case for esa_api_v20_reporting_mail_env_sender_rate_limit_env_sender_rejected_rcpts_get

        mail env sender rate limit env sender rejected rcpts  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_env_sender_rate_limit_get(self):
        """Test case for esa_api_v20_reporting_mail_env_sender_rate_limit_get

        mail env sender rate limit env sender rejected rcpts  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
