# coding: utf-8

"""
    Secure Email Gateway API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.reporting_mail_incoming_network_domain_detail_total_throttled_recipients import ReportingMailIncomingNetworkDomainDetailTotalThrottledRecipients  # noqa: E501
from swagger_client.rest import ApiException


class TestReportingMailIncomingNetworkDomainDetailTotalThrottledRecipients(unittest.TestCase):
    """ReportingMailIncomingNetworkDomainDetailTotalThrottledRecipients unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReportingMailIncomingNetworkDomainDetailTotalThrottledRecipients(self):
        """Test ReportingMailIncomingNetworkDomainDetailTotalThrottledRecipients"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.reporting_mail_incoming_network_domain_detail_total_throttled_recipients.ReportingMailIncomingNetworkDomainDetailTotalThrottledRecipients()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
