# coding: utf-8

"""
    Secure Email Gateway API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.reporting_mail_security_summary import ReportingMailSecuritySummary  # noqa: E501
from swagger_client.rest import ApiException


class TestReportingMailSecuritySummary(unittest.TestCase):
    """ReportingMailSecuritySummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReportingMailSecuritySummary(self):
        """Test ReportingMailSecuritySummary"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.reporting_mail_security_summary.ReportingMailSecuritySummary()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
