# coding: utf-8

"""
    Secure Email Gateway API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.reporting_mail_dlp_users_policy_detail_total_dlp_incidents import ReportingMailDlpUsersPolicyDetailTotalDlpIncidents  # noqa: E501
from swagger_client.rest import ApiException


class TestReportingMailDlpUsersPolicyDetailTotalDlpIncidents(unittest.TestCase):
    """ReportingMailDlpUsersPolicyDetailTotalDlpIncidents unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReportingMailDlpUsersPolicyDetailTotalDlpIncidents(self):
        """Test ReportingMailDlpUsersPolicyDetailTotalDlpIncidents"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.reporting_mail_dlp_users_policy_detail_total_dlp_incidents.ReportingMailDlpUsersPolicyDetailTotalDlpIncidents()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
