# coding: utf-8

"""
    Secure Email Gateway API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.quarantine_api import QuarantineApi  # noqa: E501
from swagger_client.rest import ApiException


class TestQuarantineApi(unittest.TestCase):
    """QuarantineApi unit test stubs"""

    def setUp(self):
        self.api = QuarantineApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_esa_api_v20_config_local_quarantines_post(self):
        """Test case for esa_api_v20_config_local_quarantines_post

        add pvo quarantine  # noqa: E501
        """
        pass

    def test_esa_api_v20_config_local_quarantines_quarantine_name_delete(self):
        """Test case for esa_api_v20_config_local_quarantines_quarantine_name_delete

        delete pvo quarantine  # noqa: E501
        """
        pass

    def test_esa_api_v20_config_local_quarantines_quarantine_name_get(self):
        """Test case for esa_api_v20_config_local_quarantines_quarantine_name_get

        get pvo quarantine details  # noqa: E501
        """
        pass

    def test_esa_api_v20_config_local_quarantines_quarantine_name_put(self):
        """Test case for esa_api_v20_config_local_quarantines_quarantine_name_put

        edit pvo quarantine  # noqa: E501
        """
        pass

    def test_esa_api_v20_config_quarantine_filters_quarantine_name_get(self):
        """Test case for esa_api_v20_config_quarantine_filters_quarantine_name_get

        get quarantine users  # noqa: E501
        """
        pass

    def test_esa_api_v20_config_quarantine_users_get(self):
        """Test case for esa_api_v20_config_quarantine_users_get

        get quarantine users  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
