# coding: utf-8

"""
    Secure Email Gateway API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.mail_incoming_ip_hostname_detail_api import MailIncomingIpHostnameDetailApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMailIncomingIpHostnameDetailApi(unittest.TestCase):
    """MailIncomingIpHostnameDetailApi unit test stubs"""

    def setUp(self):
        self.api = MailIncomingIpHostnameDetailApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_esa_api_v20_reporting_mail_incoming_ip_hostname_detail_blocked_dmarc_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_ip_hostname_detail_blocked_dmarc_get

        mail incoming ip hostname detail blocked dmarc  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_ip_hostname_detail_blocked_invalid_recipient_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_ip_hostname_detail_blocked_invalid_recipient_get

        mail incoming ip hostname detail blocked invalid recipient  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_ip_hostname_detail_blocked_reputation_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_ip_hostname_detail_blocked_reputation_get

        mail incoming ip hostname detail blocked reputation  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_ip_hostname_detail_blocked_sdr_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_ip_hostname_detail_blocked_sdr_get

        mail incoming ip hostname detail blocked sdr  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_ip_hostname_detail_bulk_mail_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_ip_hostname_detail_bulk_mail_get

        mail incoming ip hostname detail bulk mail  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_ip_hostname_detail_detected_amp_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_ip_hostname_detail_detected_amp_get

        mail incoming ip hostname detail detected amp  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_ip_hostname_detail_detected_spam_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_ip_hostname_detail_detected_spam_get

        mail incoming ip hostname detail detected spam  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_ip_hostname_detail_detected_virus_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_ip_hostname_detail_detected_virus_get

        mail incoming ip hostname detail detected virus  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_ip_hostname_detail_dns_verified_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_ip_hostname_detail_dns_verified_get

        mail incoming ip hostname detail dns verified  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_ip_hostname_detail_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_ip_hostname_detail_get

        mail incoming ip hostname detail blocked reputation  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_ip_hostname_detail_last_sender_group_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_ip_hostname_detail_last_sender_group_get

        mail incoming ip hostname detail last sender group  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_ip_hostname_detail_last_sender_group_name_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_ip_hostname_detail_last_sender_group_name_get

        mail incoming ip hostname detail last sender group name  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_ip_hostname_detail_marketing_mail_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_ip_hostname_detail_marketing_mail_get

        mail incoming ip hostname detail marketing mail  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_ip_hostname_detail_sbrs_score_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_ip_hostname_detail_sbrs_score_get

        mail incoming ip hostname detail sbrs score  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_ip_hostname_detail_social_mail_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_ip_hostname_detail_social_mail_get

        mail incoming ip hostname detail social mail  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_ip_hostname_detail_threat_content_filter_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_ip_hostname_detail_threat_content_filter_get

        mail incoming ip hostname detail threat content filter  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_ip_hostname_detail_total_clean_recipients_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_ip_hostname_detail_total_clean_recipients_get

        mail incoming ip hostname detail total clean recipients  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_ip_hostname_detail_total_graymail_recipients_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_ip_hostname_detail_total_graymail_recipients_get

        mail incoming ip hostname detail total graymail recipients  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_ip_hostname_detail_total_recipients_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_ip_hostname_detail_total_recipients_get

        mail incoming ip hostname detail total recipients  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_ip_hostname_detail_total_threat_recipients_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_ip_hostname_detail_total_threat_recipients_get

        mail incoming ip hostname detail total threat recipients  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
