# coding: utf-8

"""
    Secure Email Gateway API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.mail_dmarc_incoming_traffic_summary_api import MailDmarcIncomingTrafficSummaryApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMailDmarcIncomingTrafficSummaryApi(unittest.TestCase):
    """MailDmarcIncomingTrafficSummaryApi unit test stubs"""

    def setUp(self):
        self.api = MailDmarcIncomingTrafficSummaryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_esa_api_v20_reporting_mail_dmarc_incoming_traffic_summary_dmarc_failed_none_get(self):
        """Test case for esa_api_v20_reporting_mail_dmarc_incoming_traffic_summary_dmarc_failed_none_get

        mail dmarc incoming traffic summary dmarc failed none  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_dmarc_incoming_traffic_summary_dmarc_failed_quarantined_get(self):
        """Test case for esa_api_v20_reporting_mail_dmarc_incoming_traffic_summary_dmarc_failed_quarantined_get

        mail dmarc incoming traffic summary dmarc failed quarantined  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_dmarc_incoming_traffic_summary_dmarc_failed_rejected_get(self):
        """Test case for esa_api_v20_reporting_mail_dmarc_incoming_traffic_summary_dmarc_failed_rejected_get

        mail dmarc incoming traffic summary dmarc failed rejected  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_dmarc_incoming_traffic_summary_dmarc_failed_total_get(self):
        """Test case for esa_api_v20_reporting_mail_dmarc_incoming_traffic_summary_dmarc_failed_total_get

        mail dmarc incoming traffic summary dmarc failed total  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_dmarc_incoming_traffic_summary_dmarc_passed_get(self):
        """Test case for esa_api_v20_reporting_mail_dmarc_incoming_traffic_summary_dmarc_passed_get

        mail dmarc incoming traffic summary dmarc passed  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_dmarc_incoming_traffic_summary_dmarc_total_attempted_get(self):
        """Test case for esa_api_v20_reporting_mail_dmarc_incoming_traffic_summary_dmarc_total_attempted_get

        mail dmarc incoming traffic summary dmarc total attempted  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_dmarc_incoming_traffic_summary_get(self):
        """Test case for esa_api_v20_reporting_mail_dmarc_incoming_traffic_summary_get

        mail dmarc incoming traffic summary dmarc passed  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
