# coding: utf-8

"""
    Secure Email Gateway API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.reporting_system_api import ReportingSystemApi  # noqa: E501
from swagger_client.rest import ApiException


class TestReportingSystemApi(unittest.TestCase):
    """ReportingSystemApi unit test stubs"""

    def setUp(self):
        self.api = ReportingSystemApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_esa_api_v20_reporting_reporting_system_begin_time_get(self):
        """Test case for esa_api_v20_reporting_reporting_system_begin_time_get

        reporting system begin time  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_reporting_system_end_time_get(self):
        """Test case for esa_api_v20_reporting_reporting_system_end_time_get

        reporting system end time  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_reporting_system_get(self):
        """Test case for esa_api_v20_reporting_reporting_system_get

        reporting system begin time  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_reporting_system_heartbeat_get(self):
        """Test case for esa_api_v20_reporting_reporting_system_heartbeat_get

        reporting system heartbeat  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
