# coding: utf-8

"""
    Secure Email Gateway API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.mail_destination_domain_detail_api import MailDestinationDomainDetailApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMailDestinationDomainDetailApi(unittest.TestCase):
    """MailDestinationDomainDetailApi unit test stubs"""

    def setUp(self):
        self.api = MailDestinationDomainDetailApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_esa_api_v20_reporting_mail_destination_domain_detail_conn_dane_fail_get(self):
        """Test case for esa_api_v20_reporting_mail_destination_domain_detail_conn_dane_fail_get

        mail destination domain detail conn dane fail  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_destination_domain_detail_conn_dane_success_get(self):
        """Test case for esa_api_v20_reporting_mail_destination_domain_detail_conn_dane_success_get

        mail destination domain detail conn dane success  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_destination_domain_detail_conn_last_tls_status_get(self):
        """Test case for esa_api_v20_reporting_mail_destination_domain_detail_conn_last_tls_status_get

        mail destination domain detail conn last tls status  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_destination_domain_detail_conn_plain_get(self):
        """Test case for esa_api_v20_reporting_mail_destination_domain_detail_conn_plain_get

        mail destination domain detail conn plain  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_destination_domain_detail_conn_tls_fail_get(self):
        """Test case for esa_api_v20_reporting_mail_destination_domain_detail_conn_tls_fail_get

        mail destination domain detail conn tls fail  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_destination_domain_detail_conn_tls_opt_fail_get(self):
        """Test case for esa_api_v20_reporting_mail_destination_domain_detail_conn_tls_opt_fail_get

        mail destination domain detail conn tls opt fail  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_destination_domain_detail_conn_tls_opt_success_get(self):
        """Test case for esa_api_v20_reporting_mail_destination_domain_detail_conn_tls_opt_success_get

        mail destination domain detail conn tls opt success  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_destination_domain_detail_conn_tls_success_get(self):
        """Test case for esa_api_v20_reporting_mail_destination_domain_detail_conn_tls_success_get

        mail destination domain detail conn tls success  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_destination_domain_detail_conn_tls_total_get(self):
        """Test case for esa_api_v20_reporting_mail_destination_domain_detail_conn_tls_total_get

        mail destination domain detail conn tls total  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_destination_domain_detail_delivered_get(self):
        """Test case for esa_api_v20_reporting_mail_destination_domain_detail_delivered_get

        mail destination domain detail delivered  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_destination_domain_detail_detected_amp_get(self):
        """Test case for esa_api_v20_reporting_mail_destination_domain_detail_detected_amp_get

        mail destination domain detail detected amp  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_destination_domain_detail_detected_spam_get(self):
        """Test case for esa_api_v20_reporting_mail_destination_domain_detail_detected_spam_get

        mail destination domain detail detected spam  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_destination_domain_detail_detected_virus_get(self):
        """Test case for esa_api_v20_reporting_mail_destination_domain_detail_detected_virus_get

        mail destination domain detail detected virus  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_destination_domain_detail_encrypted_tls_get(self):
        """Test case for esa_api_v20_reporting_mail_destination_domain_detail_encrypted_tls_get

        mail destination domain detail encrypted tls  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_destination_domain_detail_get(self):
        """Test case for esa_api_v20_reporting_mail_destination_domain_detail_get

        mail destination domain detail total threat recipients  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_destination_domain_detail_hard_bounces_get(self):
        """Test case for esa_api_v20_reporting_mail_destination_domain_detail_hard_bounces_get

        mail destination domain detail hard bounces  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_destination_domain_detail_threat_content_filter_get(self):
        """Test case for esa_api_v20_reporting_mail_destination_domain_detail_threat_content_filter_get

        mail destination domain detail threat content filter  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_destination_domain_detail_total_clean_recipients_get(self):
        """Test case for esa_api_v20_reporting_mail_destination_domain_detail_total_clean_recipients_get

        mail destination domain detail total clean recipients  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_destination_domain_detail_total_recipients_get(self):
        """Test case for esa_api_v20_reporting_mail_destination_domain_detail_total_recipients_get

        mail destination domain detail total recipients  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_destination_domain_detail_total_recipients_processed_get(self):
        """Test case for esa_api_v20_reporting_mail_destination_domain_detail_total_recipients_processed_get

        mail destination domain detail total recipients processed  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_destination_domain_detail_total_threat_recipients_get(self):
        """Test case for esa_api_v20_reporting_mail_destination_domain_detail_total_threat_recipients_get

        mail destination domain detail total threat recipients  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
