# coding: utf-8

"""
    Secure Email Gateway API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.mail_incoming_traffic_summary_api import MailIncomingTrafficSummaryApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMailIncomingTrafficSummaryApi(unittest.TestCase):
    """MailIncomingTrafficSummaryApi unit test stubs"""

    def setUp(self):
        self.api = MailIncomingTrafficSummaryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_esa_api_v20_reporting_mail_incoming_traffic_summary_blocked_dmarc_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_traffic_summary_blocked_dmarc_get

        mail incoming traffic summary blocked dmarc  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_traffic_summary_blocked_invalid_recipient_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_traffic_summary_blocked_invalid_recipient_get

        mail incoming traffic summary blocked invalid recipient  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_traffic_summary_blocked_reputation_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_traffic_summary_blocked_reputation_get

        mail incoming traffic summary blocked reputation  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_traffic_summary_blocked_sdr_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_traffic_summary_blocked_sdr_get

        mail incoming traffic summary blocked sdr  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_traffic_summary_bulk_mail_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_traffic_summary_bulk_mail_get

        mail incoming traffic summary bulk mail  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_traffic_summary_detected_amp_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_traffic_summary_detected_amp_get

        mail incoming traffic summary detected amp  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_traffic_summary_detected_spam_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_traffic_summary_detected_spam_get

        mail incoming traffic summary detected spam  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_traffic_summary_detected_virus_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_traffic_summary_detected_virus_get

        mail incoming traffic summary detected virus  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_traffic_summary_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_traffic_summary_get

        mail incoming traffic summary  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_traffic_summary_ims_spam_increment_over_case_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_traffic_summary_ims_spam_increment_over_case_get

        mail incoming traffic summary ims spam increment over case  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_traffic_summary_malicious_url_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_traffic_summary_malicious_url_get

        mail incoming traffic summary malicious url  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_traffic_summary_marketing_mail_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_traffic_summary_marketing_mail_get

        mail incoming traffic summary marketing mail  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_traffic_summary_social_mail_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_traffic_summary_social_mail_get

        mail incoming traffic summary social mail  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_traffic_summary_threat_content_filter_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_traffic_summary_threat_content_filter_get

        mail incoming traffic summary threat content filter  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_traffic_summary_total_clean_recipients_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_traffic_summary_total_clean_recipients_get

        mail incoming traffic summary total clean recipients  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_traffic_summary_total_graymail_recipients_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_traffic_summary_total_graymail_recipients_get

        mail incoming traffic summary total graymail recipients  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_traffic_summary_total_recipients_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_traffic_summary_total_recipients_get

        mail incoming traffic summary total recipients  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_traffic_summary_total_threat_recipients_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_traffic_summary_total_threat_recipients_get

        mail incoming traffic summary total threat recipients  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_traffic_summary_verif_decrypt_fail_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_traffic_summary_verif_decrypt_fail_get

        mail incoming traffic summary verif decrypt fail  # noqa: E501
        """
        pass

    def test_esa_api_v20_reporting_mail_incoming_traffic_summary_verif_decrypt_success_get(self):
        """Test case for esa_api_v20_reporting_mail_incoming_traffic_summary_verif_decrypt_success_get

        mail incoming traffic summary verif decrypt success  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
