# coding: utf-8

"""
    Secure Email Gateway API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.mail_url_analysis_summary_api import MailUrlAnalysisSummaryApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMailUrlAnalysisSummaryApi(unittest.TestCase):
    """MailUrlAnalysisSummaryApi unit test stubs"""

    def setUp(self):
        self.api = MailUrlAnalysisSummaryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_esa_api_v20_reporting_mail_url_analysis_summary_get(self):
        """Test case for esa_api_v20_reporting_mail_url_analysis_summary_get

        Summary of the messages retrospected by URL Analysis.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
