# coding: utf-8

"""
    Secure Email Gateway API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.log_subscriptions_api import LogSubscriptionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLogSubscriptionsApi(unittest.TestCase):
    """LogSubscriptionsApi unit test stubs"""

    def setUp(self):
        self.api = LogSubscriptionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_esa_api_v20_config_logs_subscriptions_get(self):
        """Test case for esa_api_v20_config_logs_subscriptions_get

        Retrieve the details of all log subscriptions configured in your appliance  # noqa: E501
        """
        pass

    def test_esa_api_v20_logs_subscription_name_get(self):
        """Test case for esa_api_v20_logs_subscription_name_get

        Retrieve the details of all log files for a specific log subscription  # noqa: E501
        """
        pass

    def test_esa_api_v20_logs_subscription_name_log_file_name_get(self):
        """Test case for esa_api_v20_logs_subscription_name_log_file_name_get

        Retrieve the actual log file using the downloadUrl attribute of the response obtained from the API signature of the previous API  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
