# coding: utf-8

"""
    Secure Email Gateway API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.mailbox_auto_remediated_messages_report_api import MailboxAutoRemediatedMessagesReportApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMailboxAutoRemediatedMessagesReportApi(unittest.TestCase):
    """MailboxAutoRemediatedMessagesReportApi unit test stubs"""

    def setUp(self):
        self.api = MailboxAutoRemediatedMessagesReportApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_esa_api_v20_reporting_mail_mar_summary_get(self):
        """Test case for esa_api_v20_reporting_mail_mar_summary_get

        summary of the mailbox auto remediated messages  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
