# coding: utf-8

"""
    Secure Email Gateway API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConfigLocalQuarantinesFiltersDataQuarantineFilters(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'name': 'str',
        'esa': 'str'
    }

    attribute_map = {
        'type': 'type',
        'name': 'name',
        'esa': 'esa'
    }

    def __init__(self, type=None, name=None, esa=None):  # noqa: E501
        """ConfigLocalQuarantinesFiltersDataQuarantineFilters - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._name = None
        self._esa = None
        self.discriminator = None
        if type is not None:
            self.type = type
        if name is not None:
            self.name = name
        if esa is not None:
            self.esa = esa

    @property
    def type(self):
        """Gets the type of this ConfigLocalQuarantinesFiltersDataQuarantineFilters.  # noqa: E501


        :return: The type of this ConfigLocalQuarantinesFiltersDataQuarantineFilters.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ConfigLocalQuarantinesFiltersDataQuarantineFilters.


        :param type: The type of this ConfigLocalQuarantinesFiltersDataQuarantineFilters.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def name(self):
        """Gets the name of this ConfigLocalQuarantinesFiltersDataQuarantineFilters.  # noqa: E501


        :return: The name of this ConfigLocalQuarantinesFiltersDataQuarantineFilters.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ConfigLocalQuarantinesFiltersDataQuarantineFilters.


        :param name: The name of this ConfigLocalQuarantinesFiltersDataQuarantineFilters.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def esa(self):
        """Gets the esa of this ConfigLocalQuarantinesFiltersDataQuarantineFilters.  # noqa: E501


        :return: The esa of this ConfigLocalQuarantinesFiltersDataQuarantineFilters.  # noqa: E501
        :rtype: str
        """
        return self._esa

    @esa.setter
    def esa(self, esa):
        """Sets the esa of this ConfigLocalQuarantinesFiltersDataQuarantineFilters.


        :param esa: The esa of this ConfigLocalQuarantinesFiltersDataQuarantineFilters.  # noqa: E501
        :type: str
        """

        self._esa = esa

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConfigLocalQuarantinesFiltersDataQuarantineFilters, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigLocalQuarantinesFiltersDataQuarantineFilters):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
