# coding: utf-8

"""
    Secure Email Gateway API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConfigLocalQuarantinesGetDataQuarantineNormalActions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'quarantine_action': 'str'
    }

    attribute_map = {
        'quarantine_action': 'quarantine_action'
    }

    def __init__(self, quarantine_action=None):  # noqa: E501
        """ConfigLocalQuarantinesGetDataQuarantineNormalActions - a model defined in Swagger"""  # noqa: E501
        self._quarantine_action = None
        self.discriminator = None
        if quarantine_action is not None:
            self.quarantine_action = quarantine_action

    @property
    def quarantine_action(self):
        """Gets the quarantine_action of this ConfigLocalQuarantinesGetDataQuarantineNormalActions.  # noqa: E501


        :return: The quarantine_action of this ConfigLocalQuarantinesGetDataQuarantineNormalActions.  # noqa: E501
        :rtype: str
        """
        return self._quarantine_action

    @quarantine_action.setter
    def quarantine_action(self, quarantine_action):
        """Sets the quarantine_action of this ConfigLocalQuarantinesGetDataQuarantineNormalActions.


        :param quarantine_action: The quarantine_action of this ConfigLocalQuarantinesGetDataQuarantineNormalActions.  # noqa: E501
        :type: str
        """

        self._quarantine_action = quarantine_action

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConfigLocalQuarantinesGetDataQuarantineNormalActions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigLocalQuarantinesGetDataQuarantineNormalActions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
