# coding: utf-8

"""
    Secure Email Gateway API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MessagetrackingRejectedConnectionsAttributes(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'host_name': 'str',
        'icid': 'int',
        'message_status': 'str',
        'rejected': 'str',
        'sbrs': 'str',
        'sender_group': 'str',
        'sender_ip': 'str',
        'serial_number': 'str',
        'timestamp': 'str'
    }

    attribute_map = {
        'host_name': 'hostName',
        'icid': 'icid',
        'message_status': 'messageStatus',
        'rejected': 'rejected',
        'sbrs': 'sbrs',
        'sender_group': 'senderGroup',
        'sender_ip': 'senderIp',
        'serial_number': 'serialNumber',
        'timestamp': 'timestamp'
    }

    def __init__(self, host_name=None, icid=None, message_status=None, rejected=None, sbrs=None, sender_group=None, sender_ip=None, serial_number=None, timestamp=None):  # noqa: E501
        """MessagetrackingRejectedConnectionsAttributes - a model defined in Swagger"""  # noqa: E501
        self._host_name = None
        self._icid = None
        self._message_status = None
        self._rejected = None
        self._sbrs = None
        self._sender_group = None
        self._sender_ip = None
        self._serial_number = None
        self._timestamp = None
        self.discriminator = None
        if host_name is not None:
            self.host_name = host_name
        if icid is not None:
            self.icid = icid
        if message_status is not None:
            self.message_status = message_status
        if rejected is not None:
            self.rejected = rejected
        if sbrs is not None:
            self.sbrs = sbrs
        if sender_group is not None:
            self.sender_group = sender_group
        if sender_ip is not None:
            self.sender_ip = sender_ip
        if serial_number is not None:
            self.serial_number = serial_number
        if timestamp is not None:
            self.timestamp = timestamp

    @property
    def host_name(self):
        """Gets the host_name of this MessagetrackingRejectedConnectionsAttributes.  # noqa: E501


        :return: The host_name of this MessagetrackingRejectedConnectionsAttributes.  # noqa: E501
        :rtype: str
        """
        return self._host_name

    @host_name.setter
    def host_name(self, host_name):
        """Sets the host_name of this MessagetrackingRejectedConnectionsAttributes.


        :param host_name: The host_name of this MessagetrackingRejectedConnectionsAttributes.  # noqa: E501
        :type: str
        """

        self._host_name = host_name

    @property
    def icid(self):
        """Gets the icid of this MessagetrackingRejectedConnectionsAttributes.  # noqa: E501


        :return: The icid of this MessagetrackingRejectedConnectionsAttributes.  # noqa: E501
        :rtype: int
        """
        return self._icid

    @icid.setter
    def icid(self, icid):
        """Sets the icid of this MessagetrackingRejectedConnectionsAttributes.


        :param icid: The icid of this MessagetrackingRejectedConnectionsAttributes.  # noqa: E501
        :type: int
        """

        self._icid = icid

    @property
    def message_status(self):
        """Gets the message_status of this MessagetrackingRejectedConnectionsAttributes.  # noqa: E501


        :return: The message_status of this MessagetrackingRejectedConnectionsAttributes.  # noqa: E501
        :rtype: str
        """
        return self._message_status

    @message_status.setter
    def message_status(self, message_status):
        """Sets the message_status of this MessagetrackingRejectedConnectionsAttributes.


        :param message_status: The message_status of this MessagetrackingRejectedConnectionsAttributes.  # noqa: E501
        :type: str
        """

        self._message_status = message_status

    @property
    def rejected(self):
        """Gets the rejected of this MessagetrackingRejectedConnectionsAttributes.  # noqa: E501


        :return: The rejected of this MessagetrackingRejectedConnectionsAttributes.  # noqa: E501
        :rtype: str
        """
        return self._rejected

    @rejected.setter
    def rejected(self, rejected):
        """Sets the rejected of this MessagetrackingRejectedConnectionsAttributes.


        :param rejected: The rejected of this MessagetrackingRejectedConnectionsAttributes.  # noqa: E501
        :type: str
        """

        self._rejected = rejected

    @property
    def sbrs(self):
        """Gets the sbrs of this MessagetrackingRejectedConnectionsAttributes.  # noqa: E501


        :return: The sbrs of this MessagetrackingRejectedConnectionsAttributes.  # noqa: E501
        :rtype: str
        """
        return self._sbrs

    @sbrs.setter
    def sbrs(self, sbrs):
        """Sets the sbrs of this MessagetrackingRejectedConnectionsAttributes.


        :param sbrs: The sbrs of this MessagetrackingRejectedConnectionsAttributes.  # noqa: E501
        :type: str
        """

        self._sbrs = sbrs

    @property
    def sender_group(self):
        """Gets the sender_group of this MessagetrackingRejectedConnectionsAttributes.  # noqa: E501


        :return: The sender_group of this MessagetrackingRejectedConnectionsAttributes.  # noqa: E501
        :rtype: str
        """
        return self._sender_group

    @sender_group.setter
    def sender_group(self, sender_group):
        """Sets the sender_group of this MessagetrackingRejectedConnectionsAttributes.


        :param sender_group: The sender_group of this MessagetrackingRejectedConnectionsAttributes.  # noqa: E501
        :type: str
        """

        self._sender_group = sender_group

    @property
    def sender_ip(self):
        """Gets the sender_ip of this MessagetrackingRejectedConnectionsAttributes.  # noqa: E501


        :return: The sender_ip of this MessagetrackingRejectedConnectionsAttributes.  # noqa: E501
        :rtype: str
        """
        return self._sender_ip

    @sender_ip.setter
    def sender_ip(self, sender_ip):
        """Sets the sender_ip of this MessagetrackingRejectedConnectionsAttributes.


        :param sender_ip: The sender_ip of this MessagetrackingRejectedConnectionsAttributes.  # noqa: E501
        :type: str
        """

        self._sender_ip = sender_ip

    @property
    def serial_number(self):
        """Gets the serial_number of this MessagetrackingRejectedConnectionsAttributes.  # noqa: E501


        :return: The serial_number of this MessagetrackingRejectedConnectionsAttributes.  # noqa: E501
        :rtype: str
        """
        return self._serial_number

    @serial_number.setter
    def serial_number(self, serial_number):
        """Sets the serial_number of this MessagetrackingRejectedConnectionsAttributes.


        :param serial_number: The serial_number of this MessagetrackingRejectedConnectionsAttributes.  # noqa: E501
        :type: str
        """

        self._serial_number = serial_number

    @property
    def timestamp(self):
        """Gets the timestamp of this MessagetrackingRejectedConnectionsAttributes.  # noqa: E501


        :return: The timestamp of this MessagetrackingRejectedConnectionsAttributes.  # noqa: E501
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this MessagetrackingRejectedConnectionsAttributes.


        :param timestamp: The timestamp of this MessagetrackingRejectedConnectionsAttributes.  # noqa: E501
        :type: str
        """

        self._timestamp = timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MessagetrackingRejectedConnectionsAttributes, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MessagetrackingRejectedConnectionsAttributes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
