# coding: utf-8

"""
    Secure Email Gateway API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class QuarantineBlocklistPostData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'action': 'str',
        'recipient_addresses': 'list[str]',
        'sender_list': 'list[str]'
    }

    attribute_map = {
        'action': 'action',
        'recipient_addresses': 'recipientAddresses',
        'sender_list': 'senderList'
    }

    def __init__(self, action=None, recipient_addresses=None, sender_list=None):  # noqa: E501
        """QuarantineBlocklistPostData - a model defined in Swagger"""  # noqa: E501
        self._action = None
        self._recipient_addresses = None
        self._sender_list = None
        self.discriminator = None
        if action is not None:
            self.action = action
        if recipient_addresses is not None:
            self.recipient_addresses = recipient_addresses
        if sender_list is not None:
            self.sender_list = sender_list

    @property
    def action(self):
        """Gets the action of this QuarantineBlocklistPostData.  # noqa: E501


        :return: The action of this QuarantineBlocklistPostData.  # noqa: E501
        :rtype: str
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this QuarantineBlocklistPostData.


        :param action: The action of this QuarantineBlocklistPostData.  # noqa: E501
        :type: str
        """

        self._action = action

    @property
    def recipient_addresses(self):
        """Gets the recipient_addresses of this QuarantineBlocklistPostData.  # noqa: E501


        :return: The recipient_addresses of this QuarantineBlocklistPostData.  # noqa: E501
        :rtype: list[str]
        """
        return self._recipient_addresses

    @recipient_addresses.setter
    def recipient_addresses(self, recipient_addresses):
        """Sets the recipient_addresses of this QuarantineBlocklistPostData.


        :param recipient_addresses: The recipient_addresses of this QuarantineBlocklistPostData.  # noqa: E501
        :type: list[str]
        """

        self._recipient_addresses = recipient_addresses

    @property
    def sender_list(self):
        """Gets the sender_list of this QuarantineBlocklistPostData.  # noqa: E501


        :return: The sender_list of this QuarantineBlocklistPostData.  # noqa: E501
        :rtype: list[str]
        """
        return self._sender_list

    @sender_list.setter
    def sender_list(self, sender_list):
        """Sets the sender_list of this QuarantineBlocklistPostData.


        :param sender_list: The sender_list of this QuarantineBlocklistPostData.  # noqa: E501
        :type: list[str]
        """

        self._sender_list = sender_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(QuarantineBlocklistPostData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QuarantineBlocklistPostData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
