# coding: utf-8

"""
    Secure Email Gateway API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class QuarantineMessagesDetailsPvoDataAttributesMessageDetails(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'recipient': 'list[str]',
        'sender': 'str',
        'subject': 'str'
    }

    attribute_map = {
        'recipient': 'recipient',
        'sender': 'sender',
        'subject': 'subject'
    }

    def __init__(self, recipient=None, sender=None, subject=None):  # noqa: E501
        """QuarantineMessagesDetailsPvoDataAttributesMessageDetails - a model defined in Swagger"""  # noqa: E501
        self._recipient = None
        self._sender = None
        self._subject = None
        self.discriminator = None
        if recipient is not None:
            self.recipient = recipient
        if sender is not None:
            self.sender = sender
        if subject is not None:
            self.subject = subject

    @property
    def recipient(self):
        """Gets the recipient of this QuarantineMessagesDetailsPvoDataAttributesMessageDetails.  # noqa: E501


        :return: The recipient of this QuarantineMessagesDetailsPvoDataAttributesMessageDetails.  # noqa: E501
        :rtype: list[str]
        """
        return self._recipient

    @recipient.setter
    def recipient(self, recipient):
        """Sets the recipient of this QuarantineMessagesDetailsPvoDataAttributesMessageDetails.


        :param recipient: The recipient of this QuarantineMessagesDetailsPvoDataAttributesMessageDetails.  # noqa: E501
        :type: list[str]
        """

        self._recipient = recipient

    @property
    def sender(self):
        """Gets the sender of this QuarantineMessagesDetailsPvoDataAttributesMessageDetails.  # noqa: E501


        :return: The sender of this QuarantineMessagesDetailsPvoDataAttributesMessageDetails.  # noqa: E501
        :rtype: str
        """
        return self._sender

    @sender.setter
    def sender(self, sender):
        """Sets the sender of this QuarantineMessagesDetailsPvoDataAttributesMessageDetails.


        :param sender: The sender of this QuarantineMessagesDetailsPvoDataAttributesMessageDetails.  # noqa: E501
        :type: str
        """

        self._sender = sender

    @property
    def subject(self):
        """Gets the subject of this QuarantineMessagesDetailsPvoDataAttributesMessageDetails.  # noqa: E501


        :return: The subject of this QuarantineMessagesDetailsPvoDataAttributesMessageDetails.  # noqa: E501
        :rtype: str
        """
        return self._subject

    @subject.setter
    def subject(self, subject):
        """Sets the subject of this QuarantineMessagesDetailsPvoDataAttributesMessageDetails.


        :param subject: The subject of this QuarantineMessagesDetailsPvoDataAttributesMessageDetails.  # noqa: E501
        :type: str
        """

        self._subject = subject

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(QuarantineMessagesDetailsPvoDataAttributesMessageDetails, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QuarantineMessagesDetailsPvoDataAttributesMessageDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
